name: Run API Tests - Generate NEWMAN report

on:
  push:
    branches:
      - main

jobs:
  run-newman-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Ensure Node.js version >= 16 for Newman

      # Step 3: Install Newman and HTML Reporter
      - name: Install Newman
        run: npm install -g newman newman-reporter-html

      # Step 4: Verify Postman collection and environment files exist
      - name: Verify Postman files
        run: |
          echo " Checking for Postman collection and environment files..."
          if [[ ! -f "ReqRes API Testing.postman_collection.json" ]]; then
            echo " Collection file not found!" && exit 1
          fi
          if [[ ! -f "ReqRes API.postman_environment.json" ]]; then
            echo " Environment file not found!" && exit 1
          fi
          echo " Postman collection and environment files found."

      # Step 5: Create 'newman' folder before generating the report
      - name: Create newman folder
        run: mkdir -p newman

      # Step 6: Run Postman tests and generate HTML report
      - name: Run Postman tests and generate HTML report
        env:
          CI: true  # Ensure Newman recognizes the CI environment
        run: |
          echo " Running Newman tests..."
          newman run "ReqRes API Testing.postman_collection.json" \
            -e "ReqRes API.postman_environment.json" \
            -r html,cli \
            --reporter-html-export newman/index.html || echo "⚠ Newman test run completed with some errors."

      # Step 7: Verify report generation
      - name: Verify report generation
        run: |
          if [ -d "newman" ] && [ -f "newman/index.html" ]; then
            echo " Report generated successfully."
            ls -al newman
          else
            echo " Report not found! Newman test execution might have failed."
            exit 1
          fi

      # Step 8: Deploy report to GitHub Pages
      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: newman  # Deploy the 'newman' folder to GitHub Pages

      # Step 9: Confirm deployment
      - name: Confirm Deployment
        run: echo " GitHub Pages deployment complete! Check the report at https://<your-github-username>.github.io/<your-repo-name>/"
