name: Run API Tests - Generate NEWMAN report

on:
  push:
    branches:
      - main

jobs:
  run-newman-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Ensure Node.js version >= 16 for Newman

      # Step 3: Install Newman and HTML Reporter
      - name: Install Newman
        run: npm install -g newman newman-reporter-html

      # Step 4: Run Postman tests and generate HTML report
      - name: Run Postman tests and generate HTML report
        run: |
          newman run ReqRes API Testing.postman_collection.json -e ReqRes API.postman_environment.json -r html,cli --reporter-html-export newman/index.html || true  # Export to index.html

      # Step 5: List files in the newman folder to confirm report generation
      - name: List files in newman folder
        run: ls -al newman


      # Step 6: Deploy report to GitHub Pages
      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: newman  # Deploy the 'newman' folder to GitHub Pages

      # Step 7: Confirm deployment
      - name: Confirm Deployment
        run: echo "GitHub Pages deployment complete!"
